# Generated by Django 5.2.8 on 2025-11-22 07:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=200, unique=True, verbose_name='Razón Social')),
                ('rut', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='RUT')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('telefono_empresa', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Empresa')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empresa (B2B)',
                'verbose_name_plural': 'Empresas (B2B)',
            },
        ),
        migrations.CreateModel(
            name='Interes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Interés')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name_plural': 'Intereses',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_venta', models.DecimalField(decimal_places=0, max_digits=10)),
                ('esta_disponible', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('stock_actual', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Productos (Kits)',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('comuna_vive', models.CharField(blank=True, max_length=100, null=True, verbose_name='Comuna')),
                ('tipo_cliente', models.CharField(choices=[('B2C', 'Persona Natural'), ('B2B', 'Contacto Empresa')], default='B2C', max_length=3, verbose_name='Tipo')),
                ('estado_ciclo', models.CharField(choices=[('LEAD', 'Lead (Potencial)'), ('PROSPECTO', 'Prospecto Calificado'), ('CLIENTE', 'Cliente Activo'), ('INACTIVO', 'Cliente Inactivo')], default='LEAD', max_length=20, verbose_name='Estado del Lead')),
                ('origen', models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('GOOGLE', 'Google/Web'), ('REFERIDO', 'Referido por amigo'), ('EVENTO', 'Evento Presencial'), ('OTRO', 'Otro')], default='OTRO', max_length=20, verbose_name='Origen del Contacto')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactos', to='api.empresa', verbose_name='Empresa (si aplica)')),
                ('intereses_cliente', models.ManyToManyField(blank=True, related_name='clientes', to='api.interes', verbose_name='Intereses')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pagado', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pago Pendiente'), ('PAGADO', 'Pagado Completo'), ('ABONADO', 'Abonado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=10)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='api.cliente')),
            ],
            options={
                'verbose_name_plural': 'Inscripciones',
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(blank=True, max_length=254, null=True)),
                ('subject', models.CharField(max_length=255)),
                ('body_text', models.TextField(blank=True, null=True)),
                ('body_html', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Enviado'), ('FAIL', 'Fallido')], default='SUCCESS', max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inscripcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.inscripcion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Interaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LLAMADA', 'Llamada Telefónica'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Correo Electrónico'), ('REUNION', 'Reunión Presencial/Zoom')], default='EMAIL', max_length=20)),
                ('resumen', models.CharField(max_length=200, verbose_name='Resumen breve')),
                ('detalle', models.TextField(blank=True, verbose_name='Detalle de la conversación')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacciones', to='api.cliente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor/Staff')),
            ],
            options={
                'verbose_name': 'Interacción CRM',
                'verbose_name_plural': 'Bitácora de Interacciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre del Taller')),
                ('descripcion', models.TextField(verbose_name='Descripción Detallada')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='talleres/')),
                ('fecha_taller', models.DateField(verbose_name='Fecha del Taller')),
                ('hora_taller', models.TimeField(blank=True, null=True)),
                ('modalidad', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('ONLINE', 'Online')], default='PRESENCIAL', max_length=15)),
                ('precio', models.DecimalField(decimal_places=0, max_digits=10)),
                ('cupos_totales', models.IntegerField(default=10)),
                ('cupos_disponibles', models.IntegerField(default=0, verbose_name='Cupos Disponibles')),
                ('esta_activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talleres', to='api.interes')),
            ],
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='taller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='api.taller'),
        ),
        migrations.CreateModel(
            name='VentaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('monto_total', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pago Pendiente'), ('PAGADO', 'Pagado Completo'), ('ANULADO', 'Anulado')], default='PAGADO', max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_kits', to='api.cliente')),
            ],
            options={
                'verbose_name_plural': 'Ventas de Productos',
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=0, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='api.ventaproducto')),
            ],
            options={
                'verbose_name_plural': 'Detalles de Venta',
            },
        ),
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together={('cliente', 'taller')},
        ),
    ]
