# Generated by Django 5.2.8 on 2025-11-23 00:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('asunto', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Mensaje de Contacto',
                'verbose_name_plural': 'Mensajes de Contacto',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Curso')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cursos/')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=0, max_digits=10)),
                ('duracion', models.CharField(max_length=100, verbose_name='Duración (ej: 5 horas)')),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('estudiantes', models.IntegerField(default=0)),
                ('esta_activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos', to='api.interes')),
            ],
            options={
                'verbose_name': 'Curso Grabado',
                'verbose_name_plural': 'Cursos Grabados',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('extracto', models.TextField(verbose_name='Extracto (para tarjetas)')),
                ('contenido', models.TextField(verbose_name='Contenido del Post')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('esta_publicado', models.BooleanField(default=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='api.interes')),
            ],
            options={
                'verbose_name': 'Artículo de Blog',
                'verbose_name_plural': 'Blog',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
