# Generated by Django 5.2.8 on 2025-11-23 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contacto_curso_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscripcion',
            options={'verbose_name_plural': 'Inscripciones Talleres'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_taller', to='api.cliente'),
        ),
        migrations.CreateModel(
            name='InscripcionCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pagado', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pago Pendiente'), ('PAGADO', 'Pagado Completo'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=10)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('progreso', models.IntegerField(default=0, verbose_name='Progreso %')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_curso', to='api.cliente')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='api.curso')),
            ],
            options={
                'verbose_name_plural': 'Inscripciones Cursos',
                'unique_together': {('cliente', 'curso')},
            },
        ),
    ]
