# Generated by Django 5.2.8 on 2025-11-23 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_inscripcion_options_cliente_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la Lección')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('VIDEO', 'Video'), ('LECTURA', 'Lectura'), ('ACTIVIDAD', 'Actividad'), ('QUIZ', 'Quiz')], default='LECTURA', max_length=20)),
                ('orden', models.IntegerField(default=0, verbose_name='Orden')),
                ('duracion_estimada', models.IntegerField(default=0, verbose_name='Duración Estimada (minutos)')),
                ('esta_activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lección',
                'verbose_name_plural': 'Lecciones',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ContenidoLeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido_texto', models.TextField(blank=True, verbose_name='Contenido de Texto (HTML)')),
                ('url_video', models.URLField(blank=True, null=True, verbose_name='URL del Video')),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='lecciones/', verbose_name='Archivo Adjunto')),
                ('recursos_adicionales', models.TextField(blank=True, verbose_name='Recursos Adicionales (JSON o texto)')),
                ('leccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contenido', to='api.leccion')),
            ],
            options={
                'verbose_name': 'Contenido de Lección',
                'verbose_name_plural': 'Contenidos de Lecciones',
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la Actividad')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('TAREA', 'Tarea'), ('EJERCICIO', 'Ejercicio Práctico'), ('PROYECTO', 'Proyecto'), ('REFLEXION', 'Reflexión Personal')], default='TAREA', max_length=20)),
                ('instrucciones', models.TextField(verbose_name='Instrucciones Detalladas')),
                ('archivo_plantilla', models.FileField(blank=True, null=True, upload_to='actividades/', verbose_name='Plantilla o Archivo de Apoyo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='api.leccion')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la Sección')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden')),
                ('esta_activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='api.curso')),
            ],
            options={
                'verbose_name': 'Sección de Curso',
                'verbose_name_plural': 'Secciones de Curso',
                'ordering': ['orden'],
            },
        ),
        migrations.AddField(
            model_name='leccion',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecciones', to='api.seccion'),
        ),
        migrations.CreateModel(
            name='ProgresoLeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completado', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('tiempo_dedicado', models.IntegerField(default=0, verbose_name='Tiempo Dedicado (minutos)')),
                ('notas_estudiante', models.TextField(blank=True, verbose_name='Notas del Estudiante')),
                ('inscripcion_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progreso_lecciones', to='api.inscripcioncurso')),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='api.leccion')),
            ],
            options={
                'verbose_name': 'Progreso de Lección',
                'verbose_name_plural': 'Progresos de Lecciones',
                'unique_together': {('inscripcion_curso', 'leccion')},
            },
        ),
    ]
