# Generated by Django 5.2.8 on 2025-11-25 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_resena'),
    ]

    operations = [
        migrations.AddField(
            model_name='resena',
            name='interes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resenas', to='api.interes'),
        ),
    ]
