# Generated by Django 5.2.8 on 2025-11-28 01:30

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_transaccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='inscripcion_curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='api.inscripcioncurso'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='comprobante',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.transaction_file_path, verbose_name='Comprobante de Pago'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='inscripcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='api.inscripcion'),
        ),
    ]
