# Generated by Django 5.2.8 on 2025-11-28 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_transaccion_inscripcion_curso_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='taller',
        ),
        migrations.AlterUniqueTogether(
            name='inscripcioncurso',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='inscripcioncurso',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='inscripcioncurso',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='inscripcion_curso',
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('monto_pagado', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pago Pendiente'), ('PAGADO', 'Pagado Completo'), ('ABONADO', 'Abonado'), ('ANULADO', 'Anulado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=10)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('progreso', models.IntegerField(default=0, verbose_name='Progreso %')),
                ('completado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='api.cliente')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('ultima_leccion_vista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments_vistos', to='api.leccion')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
            },
        ),
        migrations.AlterUniqueTogether(
            name='progresoleccion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='progresoleccion',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progreso_lecciones', to='api.enrollment'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='inscripcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.enrollment'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='inscripcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='api.enrollment'),
        ),
        migrations.AlterUniqueTogether(
            name='progresoleccion',
            unique_together={('enrollment', 'leccion')},
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['content_type', 'object_id'], name='api_enrollm_content_cc82d8_idx'),
        ),
        migrations.DeleteModel(
            name='Inscripcion',
        ),
        migrations.RemoveField(
            model_name='progresoleccion',
            name='inscripcion_curso',
        ),
        migrations.DeleteModel(
            name='InscripcionCurso',
        ),
    ]
