# Generated by Django 5.2.8 on 2025-12-02 06:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_orden_detalleorden_transaccion_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='controlar_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='es_fisico',
            field=models.BooleanField(default=False, help_text='¿Requiere envío/despacho?'),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_critico',
            field=models.PositiveIntegerField(default=5, help_text='Alerta de stock bajo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_actual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('inscripcion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificado', to='api.enrollment')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
            },
        ),
    ]
