# Generated by Django 5.2.8 on 2025-12-02 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_producto_controlar_stock_producto_es_fisico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('validez_dias', models.IntegerField(default=15, verbose_name='Días de Validez')),
                ('monto_total', models.DecimalField(decimal_places=0, max_digits=10)),
                ('items_json', models.JSONField(verbose_name='Detalle de Items (Snapshot)')),
                ('razon_social', models.CharField(blank=True, max_length=200, null=True)),
                ('rut_empresa', models.CharField(blank=True, max_length=20, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='api.cliente')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
