# Generated by Django 5.2.8 on 2025-12-02 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_cotizacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaEspera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('notificado', models.BooleanField(default=False)),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista_espera', to='api.taller')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lista de Espera',
                'verbose_name_plural': 'Listas de Espera',
                'ordering': ['fecha_registro'],
                'unique_together': {('taller', 'usuario')},
            },
        ),
    ]
