# Generated by Django 5.2.8 on 2025-12-03 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_listaespera'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='tipo_cliente',
            field=models.CharField(choices=[('B2C', 'B2C (Personas)'), ('B2B', 'B2B (Empresas)'), ('AMBOS', 'Ambos')], default='AMBOS', max_length=10, verbose_name='Tipo de Cliente'),
        ),
        migrations.AddField(
            model_name='taller',
            name='tipo_cliente',
            field=models.CharField(choices=[('B2C', 'B2C (Personas)'), ('B2B', 'B2B (Empresas)'), ('AMBOS', 'Ambos')], default='AMBOS', max_length=10, verbose_name='Tipo de Cliente'),
        ),
    ]
