# Generated by Django 5.2.8 on 2025-12-08 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_curso_tipo_cliente_taller_tipo_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='estado_entrega',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de envío'), ('EN_PREPARACION', 'En preparación'), ('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20),
        ),
    ]
